version: '3.3'
services: 
  web: 
    image: neemarawat/myapache_code
    container_name: akweb
    ports:
      - "2233:80"
    volumes:
      - ./apache/:/var/www/html/           # hostPath:containerPath:mode

  myweb: 
    build: ./apache/ 
    image: mynewIMG
    container_name: akweb
    ports: 
      - "2244:80"
    volumes: 
      - ./apache/:/